"""Add publication and expiration date

Revision ID: 18e65d8b08cf
Revises: 6d1dd089cb98
Create Date: 2026-05-28 19:21:40.045058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e65d8b08cf'
down_revision: Union[str, Sequence[str], None] = '6d1dd089cb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offers', sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_offers', sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_offers', 'expiration_date')
    op.drop_column('job_offers', 'publication_date')
    # ### end Alembic commands ###
