"""Initial schemas

Revision ID: 2614334a85cb
Revises: 
Create Date: 2026-04-11 13:10:38.515041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2614334a85cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('experience_levels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exp_level', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exp_level')
    )
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city')
    )
    op.create_table('sites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('specializations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('specialization', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('specialization')
    )
    op.create_table('technologies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('technologies', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technologies')
    )
    op.create_table('users',
    sa.Column('id_keycloak', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_keycloak'),
    sa.UniqueConstraint('email')
    )
    op.create_table('work_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_type')
    )
    op.create_table('job_offers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('exp_level_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('work_type_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('specialization_id', sa.Uuid(), nullable=False),
    sa.Column('technology_id', sa.Uuid(), nullable=False),
    sa.Column('salary_from', sa.Float(), nullable=True),
    sa.Column('salary_to', sa.Float(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exp_level_id'], ['experience_levels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exp_level_id', sa.Uuid(), nullable=False),
    sa.Column('raw_cv', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exp_level_id'], ['experience_levels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_keycloak'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_offer_location',
    sa.Column('job_offer_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_offer_id', 'location_id')
    )
    op.create_table('job_offer_technology',
    sa.Column('job_offer_id', sa.Uuid(), nullable=False),
    sa.Column('technology_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_offer_id', 'technology_id')
    )
    op.create_table('user_profile_technology',
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('technology_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_profile_id', 'technology_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile_technology')
    op.drop_table('job_offer_technology')
    op.drop_table('job_offer_location')
    op.drop_table('user_profiles')
    op.drop_table('job_offers')
    op.drop_table('work_types')
    op.drop_table('users')
    op.drop_table('technologies')
    op.drop_table('specializations')
    op.drop_table('sites')
    op.drop_table('locations')
    op.drop_table('experience_levels')
    op.drop_table('companies')
    # ### end Alembic commands ###
