"""refactor: Abstract lookups

Revision ID: c69be3eedb51
Revises: 320f96561bc9
Create Date: 2026-04-12 10:53:24.730774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69be3eedb51'
down_revision: Union[str, Sequence[str], None] = '320f96561bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('companies_company_name_key'), 'companies', type_='unique')
    op.create_unique_constraint(None, 'companies', ['name'])
    op.drop_column('companies', 'company_name')
    op.add_column('experience_levels', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('experience_levels_exp_level_key'), 'experience_levels', type_='unique')
    op.create_unique_constraint(None, 'experience_levels', ['name'])
    op.drop_column('experience_levels', 'exp_level')
    op.add_column('locations', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('locations_city_key'), 'locations', type_='unique')
    op.create_unique_constraint(None, 'locations', ['name'])
    op.drop_column('locations', 'city')
    op.add_column('sites', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('sites_url_key'), 'sites', type_='unique')
    op.create_unique_constraint(None, 'sites', ['name'])
    op.drop_column('sites', 'url')
    op.add_column('specializations', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('specializations_specialization_key'), 'specializations', type_='unique')
    op.create_unique_constraint(None, 'specializations', ['name'])
    op.drop_column('specializations', 'specialization')
    op.add_column('technologies', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('technologies_technologies_key'), 'technologies', type_='unique')
    op.create_unique_constraint(None, 'technologies', ['name'])
    op.drop_column('technologies', 'technologies')
    op.add_column('work_types', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('work_types_work_type_key'), 'work_types', type_='unique')
    op.create_unique_constraint(None, 'work_types', ['name'])
    op.drop_column('work_types', 'work_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_types', sa.Column('work_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'work_types', type_='unique')
    op.create_unique_constraint(op.f('work_types_work_type_key'), 'work_types', ['work_type'], postgresql_nulls_not_distinct=False)
    op.drop_column('work_types', 'name')
    op.add_column('technologies', sa.Column('technologies', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'technologies', type_='unique')
    op.create_unique_constraint(op.f('technologies_technologies_key'), 'technologies', ['technologies'], postgresql_nulls_not_distinct=False)
    op.drop_column('technologies', 'name')
    op.add_column('specializations', sa.Column('specialization', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'specializations', type_='unique')
    op.create_unique_constraint(op.f('specializations_specialization_key'), 'specializations', ['specialization'], postgresql_nulls_not_distinct=False)
    op.drop_column('specializations', 'name')
    op.add_column('sites', sa.Column('url', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sites', type_='unique')
    op.create_unique_constraint(op.f('sites_url_key'), 'sites', ['url'], postgresql_nulls_not_distinct=False)
    op.drop_column('sites', 'name')
    op.add_column('locations', sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'locations', type_='unique')
    op.create_unique_constraint(op.f('locations_city_key'), 'locations', ['city'], postgresql_nulls_not_distinct=False)
    op.drop_column('locations', 'name')
    op.add_column('experience_levels', sa.Column('exp_level', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'experience_levels', type_='unique')
    op.create_unique_constraint(op.f('experience_levels_exp_level_key'), 'experience_levels', ['exp_level'], postgresql_nulls_not_distinct=False)
    op.drop_column('experience_levels', 'name')
    op.add_column('companies', sa.Column('company_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_unique_constraint(op.f('companies_company_name_key'), 'companies', ['company_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('companies', 'name')
    # ### end Alembic commands ###
